### ISSUE TITLE
Strange characters in temperature

### ISSUE THREAD

**Issue by KennyStier** [NikoFresh/WeeWX-mobile-app#1]
![Screenshot_20200401-005235](https://user-images.githubusercontent.com/4749568/78100589-30020380-73b3-11ea-9ca5-a5696db2e4f0.png)
For some reason the app displays strange characters in the temperature. I checked the JSON file and the character does not appear in it. https://wx.millhousen.com/app.json

I have already changed the encoding from html_entities to utf8.
Thanks for the cool project!

**Comment by NikoFresh** [comment]
I should have fixed it with the latest commit.
I don't actually know why Flutter was displaying 'Â°' instead of just '°', since with celsius there wasn't any problem.
